# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: HD-BBM 实验室
#  params:
  description: HD-BBM 实验室
#  menu:
  main:
  - name: 首页
    url: '#about'
    weight: 10
  - name: 成员
    url: '#project'
    weight: 20
  - name: 出版物
    url: '#featured'
    weight: 30
  - name: 新闻
    url: '#posts'
    weight: 40
  - name: 基金
    url: '#accomplishments'
    weight: 50
  - name: 联系我们
    url: '#contact'
    weight: 60

#    main:
#      - name: 
#        url: '#about'
#        weight: 1
